apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog
spec:
  project: example
  destination:
    namespace: blog
    server: https://kubernetes.default.svc
  source:
    path: apps/blog/base
    repoURL: https://github.com/kubeshop/argo-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
